### ISSUE TITLE
SessionNotCreatedError: session not created exception.

### ISSUE THREAD

**Issue by hemanth** [jaridmargolin/inspect-process#10]
```sh
$ inspect _mocha --no-timeouts
```

```sh
/Users/hemanth/.nvm/versions/node/v6.9.1/lib/node_modules/inspect-process/node_modules/selenium-webdriver/lib/promise.js:2497
        throw error;
        ^

SessionNotCreatedError: session not created exception
from unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"57746.1","isDefault":true},"id":1,"name":"","origin":"://"}
  (Session info: chrome=54.0.2840.71)
  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Mac OS X 10.11.6 x86_64)
    at WebDriverError (/Users/hemanth/.nvm/versions/node/v6.9.1/lib/node_modules/inspect-process/node_modules/selenium-webdriver/lib/error.js:27:5)
    at SessionNotCreatedError (/Users/hemanth/.nvm/versions/node/v6.9.1/lib/node_modules/inspect-process/node_modules/selenium-webdriver/lib/error.js:214:5)
    at Object.checkLegacyResponse (/Users/hemanth/.nvm/versions/node/v6.9.1/lib/node_modules/inspect-process/node_modules/selenium-webdriver/lib/error.js:505:15)
    at parseHttpResponse (/Users/hemanth/.nvm/versions/node/v6.9.1/lib/node_modules/inspect-process/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/Users/hemanth/.nvm/versions/node/v6.9.1/lib/node_modules/inspect-process/node_modules/selenium-webdriver/lib/http.js:440:13)
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/Users/hemanth/.nvm/versions/node/v6.9.1/lib/node_modules/inspect-process/node_modules/selenium-webdriver/lib/webdriver.js:776:24)
    at Function.createSession (/Users/hemanth/.nvm/versions/node/v6.9.1/lib/node_modules/inspect-process/node_modules/selenium-webdriver/chrome.js:709:29)
    at createDriver (/Users/hemanth/.nvm/versions/node/v6.9.1/lib/node_modules/inspect-process/node_modules/selenium-webdriver/index.js:167:33)
    at Builder.build (/Users/hemanth/.nvm/versions/node/v6.9.1/lib/node_modules/inspect-process/node_modules/selenium-webdriver/index.js:639:16)
    at new module.exports (/Users/hemanth/.nvm/versions/node/v6.9.1/lib/node_modules/inspect-process/lib/devtools.js:21:62)
    at /Users/hemanth/.nvm/versions/node/v6.9.1/lib/node_modules/inspect-process/lib/index.js:51:22
    at inspectProcess (/Users/hemanth/.nvm/versions/node/v6.9.1/lib/node_modules/inspect-process/lib/index.js:45:10)
    at findOpenPort.then (/Users/hemanth/.nvm/versions/node/v6.9.1/lib/node_modules/inspect-process/lib/index.js:27:21)
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Module.runMain (module.js:606:11)
From: Task: WebDriver.manage().window().getSize()
    at thenableWebDriverProxy.schedule (/Users/hemanth/.nvm/versions/node/v6.9.1/lib/node_modules/inspect-process/node_modules/selenium-webdriver/lib/webdriver.js:815:17)
    at Window.getSize (/Users/hemanth/.nvm/versions/node/v6.9.1/lib/node_modules/inspect-process/node_modules/selenium-webdriver/lib/webdriver.js:1562:25)
    at Devtools._resize (/Users/hemanth/.nvm/versions/node/v6.9.1/lib/node_modules/inspect-process/lib/devtools.js:49:17)
    at Devtools.open (/Users/hemanth/.nvm/versions/node/v6.9.1/lib/node_modules/inspect-process/lib/devtools.js:25:15)
    at Socket.proc.stderr.on (/Users/hemanth/.nvm/versions/node/v6.9.1/lib/node_modules/inspect-process/lib/index.js:68:25)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:548:20)
```

**Comment by jaridmargolin** [comment]
Looks like it is attempting to use an old chromedriver which results in the following error https://bugs.chromium.org/p/chromedriver/issues/detail?id=1464:

```
  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Mac OS X 10.11.6 x86_64)
```

It should be installing chromedriver 2.24.1 (https://github.com/jaridmargolin/inspect-process/blob/master/package.json#L25).

**Comment by jaridmargolin** [comment]
Were there any errors during installation?

**Comment by hemanth** [comment]
First attempt had a network failure in fetching the chromedriver, later it installation went well and then the issue reported above.

**Comment by jaridmargolin** [comment]
Hmmm... Wonder if an uninstall / reinstall would fix the issue.

**Comment by hemanth** [comment]
Same after:

``` sh
npm install -g inspect-process
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
/Users/hemanth/.nvm/versions/node/v6.9.1/bin/inspect -> /Users/hemanth/.nvm/versions/node/v6.9.1/lib/node_modules/inspect-process/bin/inspect.js

> chromedriver@2.25.1 install /Users/hemanth/.nvm/versions/node/v6.9.1/lib/node_modules/inspect-process/node_modules/chromedriver
> node install.js

Downloading http://chromedriver.storage.googleapis.com/2.25/chromedriver_mac64.zip
Saving to /var/folders/n1/0x2_nvf51wg20p1gyht0tx3r3kfms6/T/chromedriver/chromedriver_mac64.zip
Receiving...
Received 782K...
Received 1564K...
Received 2346K...
Received 3128K...
Received 3910K...
Received 4456K total.
Extracting zip contents
Copying to target path /Users/hemanth/.nvm/versions/node/v6.9.1/lib/node_modules/inspect-process/node_modules/chromedriver/lib/chromedriver
Fixing file permissions
Done. ChromeDriver binary available at /Users/hemanth/.nvm/versions/node/v6.9.1/lib/node_modules/inspect-process/node_modules/chromedriver/lib/chromedriver/chromedriver
/Users/hemanth/.nvm/versions/node/v6.9.1/lib
└─┬ inspect-process@0.1.1 
  ├─┬ chromedriver@2.25.1 
  │ ├── adm-zip@0.4.7 
  │ ├── kew@0.5.0 
  │ ├─┬ mkdirp@0.5.1 
  │ │ └── minimist@0.0.8 
  │ ├─┬ npmconf@2.1.2 
  │ │ ├─┬ config-chain@1.1.11 
  │ │ │ └── proto-list@1.2.4 
  │ │ ├── inherits@2.0.3 
  │ │ ├── ini@1.3.4 
  │ │ ├─┬ nopt@3.0.6 
  │ │ │ └── abbrev@1.0.9 
  │ │ ├─┬ once@1.3.3 
  │ │ │ └── wrappy@1.0.2 
  │ │ ├─┬ osenv@0.1.3 
  │ │ │ └── os-homedir@1.0.2 
  │ │ ├── semver@4.3.6 
  │ │ └── uid-number@0.0.5 
  │ └─┬ rimraf@2.5.4 
  │   └─┬ glob@7.1.1 
  │     ├── fs.realpath@1.0.0 
  │     ├── inflight@1.0.6 
  │     ├─┬ minimatch@3.0.3 
  │     │ └─┬ brace-expansion@1.1.6 
  │     │   ├── balanced-match@0.4.2 
  │     │   └── concat-map@0.0.1 
  │     └── path-is-absolute@1.0.1 
  ├── exit-hook@1.1.1 
  ├── lodash@4.16.6 
  ├─┬ portfinder@1.0.9 
  │ ├── async@1.5.2 
  │ └─┬ debug@2.2.0 
  │   └── ms@0.7.1 
  ├─┬ selenium-webdriver@3.0.0 
  │ ├─┬ tmp@0.0.30 
  │ │ └── os-tmpdir@1.0.2 
  │ └─┬ xml2js@0.4.17 
  │   ├── sax@1.2.1 
  │   └── xmlbuilder@4.2.1 
  └─┬ which@1.2.11 
    └── isexe@1.1.2 
```

**Comment by hemanth** [comment]
BTW I running `inspect _mocha` on [this](https://github.com/hemanth/github-avatar-url) repo.

**Comment by jaridmargolin** [comment]
Ok. I am assuming you have an older version of chromedriver on your machine and as a result it is not playing nicely.

I should be able to specify the exact path to chromedriver on instantiation rather than relying on it being set as an env var in the PATH.

I'll try to get a patch up ASAP. Thanks for the report.

**Comment by jaridmargolin** [comment]
Was able to get a patch out. Could you try installing latest to confirm it resolves your issue?

**Comment by jaridmargolin** [comment]
Closing.. Please let me know if the issue persists.
